### ISSUE TITLE
query kudu caught "authentication token expired" error

### ISSUE THREAD

**Issue by yorkart** [MartinWeindel/presto-kudu#2]
After running presto for some time ,  the presto-kudu plugin is not work.
kudu master print error:
```
W0209 17:45:12.619432 95794 negotiation.cc:318] Unauthorized connection attempt: Server connection negotiation failed: server connection from 172.18.32.82:12744: authentication token expired
```
Very similar:
https://issues.apache.org/jira/browse/IMPALA-5829

**Comment by MartinWeindel** [comment]
This seems to be caused by [KUDU-2013](https://issues.apache.org/jira/browse/KUDU-2013), which was resolved for Kudu Java client 1.5.0.
Up to version v0.190.1 the Presto-Kudu Connector used the Kudu Java client 1.4.0.

If you are using version v0.190.1, please replace it with the version built with Kudu Java client 1.6.0.
It is downloadable [here](https://github.com/MartinWeindel/presto-kudu/releases/tag/v0.190.1)
This version should also work for Kudu 1.4.0 and 1.5.0.

Note that there is already a newer release [v0.193.1](https://github.com/MartinWeindel/presto-kudu/releases/tag/v0.193.1) for Presto 0.193. This new version uses the Kudu Java client 1.6.0, too.

Please give some feedback, if this really resolves your issue.

**Comment by yorkart** [comment]
Thank you very much for your reply.
I've upgraded to version 0.193.1 and now it's work fine.

**Comment by MartinWeindel** [comment]
Great!
